export const discover = [
    {
        id: 1,
        type: ['Technology', 'Programming'],
        title: 'Go Concurrency Workshop',
        date: 'Aug 22, 2026',
        hour: '09:00 WIB',
        at: 'Bandung',
        participant: 48,
        slot: 100,
        img: "src/assets/images/event/go.jpg",
    },
    {
        id: 2,
        type: ['AI', 'Design'],
        title: 'AI Product Design Summit',
        date: 'Sep 5, 2026',
        hour: '08:30 WIB',
        at: 'Jakarta',
        participant: 234,
        slot: 300,
        img: 'src/assets/images/event/ai.jpg',
    },
    {
        id: 3,
        type: ['Technology', 'Programming'],
        title: 'Frontend Craft Conference',
        date: 'Oct 12, 2026',
        hour: '09:00 WIB',
        at: 'Bandung',
        participant: 167,
        slot: 200,
        img: 'src/assets/images/event/fe.jpg',
    },
    {
        id: 4,
        type: ['Bussiness', 'Career'],
        title: 'Product Management Masterclass',
        date: 'Sep 18, 2026',
        hour: '10:00 WIB',
        at: 'Online',
        participant: 89,
        slot: 150,
        img: 'src/assets/images/event/pmm.jpg',
    },
    {
        id: 5,
        type: ['Music'],
        title: 'Music Production Bootcamp',
        date: 'Nov 3, 2026',
        hour: '13:00 WIB',
        at: 'Surabaya',
        participant: 45,
        slot: 60,
        img: 'src/assets/images/event/music.jpg',
    },
    {
        id: 6,
        type: ['Business'],
        title: 'Startup Pitch Night',
        date: 'Sep 28, 2026',
        hour: '18:30 WIB',
        at: 'Jakarta',
        participant: 120,
        slot: 120,
        img: 'src/assets/images/event/music.jpg',
    }
];

export const communities = [
    {
        id: 'p-01',
        title: 'Bandung Go Community',
        desc: 'The Premier Go programming community in Bandung — weekly meetups, workshops, and learning',
        type: ['Technology', 'Programming'],
        member: 847,
        agenda: 3,
        img: 'src/assets/images/communities/go.jpg',
    },
    {
        id: 'p-02',
        title: 'Jakarta AI & ML Club',
        desc: 'Researchers, practitioners, and enthusiasts, exploring, machine learning, LLMs, and the',
        type: ['AI', 'Technology'],
        member: 2341,
        agenda: 5,
        img: 'src/assets/images/communities/ai.jpg',
    },
    {
        id: 'p-03',
        title: 'Indonesia Frontend Devs',
        desc: 'The largest frontend, community in indonesia. React, Vue, Svelte, performance, accessibility',
        type: ['Technology', 'Programming'],
        member: 5621,
        agenda: 4,
        img: 'src/assets/images/communities/fe.jpg',
    },
    {
        id: 'p-04',
        title: 'Product Minds Indonesia',
        desc: 'Product Managers, designers, and builders sharing frameworks, tools, and career.',
        type: ['Business', 'Career'],
        member: 1203,
        agenda: 2,
        img: 'src/assets/images/communities/pmi.jpg',
    },
];

export const testi = [
    {
        id: 't-001',
        name: 'Raisa Nurdiana',
        role: 'FrontEnd Engineer',
        company: 'Cakrawala Digital',
        conf: 'EventHub completely changed how i network. I met my current co-founder at a Jakarta AI meetup i found here. The community pages make it so easy to find people who are into the same things.',
    },
    {
        id: 't-002',
        name: 'Bimo Hartanto',
        role: 'Product Manager',
        company: 'Nusantara Labs',
        conf: 'We used to manage event registrations over WhatsApp groups. Switching to EventHub as our organizer platform cut our admin overhead in half and attendance actually went up',
    },
    {
        id: 't-003',
        name: 'Indira Kusuma',
        role: 'UX Designer',
        company: 'Aruna Kreasi Studio',
        conf: 'I Love that i can filter by city and category in one place. Found a design sprint workshop in Bandung I never would have discovered otherwise — ended up being one of the best events Ive attended',
    },
]